baseURL = "https://dede-20191130.github.io/learnerBlog"
languageCode = "ja"
title = "学習者のブログ　◆プログラミング等"
theme = "Clarity"

# DefaultContentLanguage = "ja"

[params]
author = "dede-20191130"
twitter = "@D20191130"
largeTwitterCard = false # set to true if you want to show a large twitter card image. The default is a small twitter card image
introDescription = "VBAから入り、プログラミング、コンピュータ科学等を勉強中。"
# description = "" # set your site's description here. will be use for home page content meta tags (seo). Alternatively set this description in your homepage content file i.e content/_index.md. Whatever is set in the latter will take precedence

numberOfTagsShown = 14

# Google analytics Id
ga_analytics = "XXXXXXXXXX"

# directory(s) where your articles are located
mainSections = ["posts"] # see config details here https://gohugo.io/functions/where/#mainsections

# Set the collapsed mobile navigation to either appear from the left or the right
mobileNavigation = "left" # if you prefer right change to 'right'

# Label Non inline images on an article body
figurePositionShow = true # toggle on or off globally
# you can toggle this behaviour on or off on per page using the same variable inside your articles frontmatter
figurePositionLabel = "Figure" # the text before image number e.g Figure 1.0

# sets the maximum number of lines per codeblock. The codeblock will however be scrollable and expandable.
codeMaxLines = 12

# disable showing line numbers by default. Switch to `true` if you'd rather have them on.
codeLineNumbers = true 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# Deploy
publishDir = "docs"
