@startuml

title 画面遷移図(2)

state 見積書作成処理系 #FFFF77{
    [*] -[#blue,bold]-> 見積書項目設定画面
    見積書項目設定画面:entry/初期表示
    見積書項目設定画面:do/見積書テンプレートのプレビュー表示
    見積書項目設定画面:exit/メニューに戻る
    見積書項目設定画面 --> 会社名選択画面: 検索ボタン押下
    会社名選択画面:entry/会社名データ一覧表示
    会社名選択画面:exit/見積書項目設定に戻る
    会社名選択画面 --> 見積書項目設定画面: レコード選択\nOK押下
    見積書項目設定画面 --> 担当者選択画面: 検索ボタン押下
    担当者選択画面:entry/人名データ一覧表示
    担当者選択画面:exit/見積書項目設定に戻る
    担当者選択画面 --> 見積書項目設定画面: レコード選択\nOK押下
    見積書項目設定画面 --> 見積書項目データ利用画面: [作成済み見積書データ利用]ボタン押下
    見積書項目データ利用画面:entry/過去作成分の見積書項目データ取得
    見積書項目データ利用画面:do/反映項目の絞り込み
    見積書項目データ利用画面:exit/見積書項目設定に戻る
    見積書項目データ利用画面 --> 見積書項目設定画面: レコード選択\nOK押下
    見積書項目設定画面 ---[#blue,bold]-> 見積書_項目リスト作成画面: 次へ
    見積書_項目リスト作成画面:entry/見積書商品・サービスのリスト表示
    見積書_項目リスト作成画面:do/見積書作成処理実行
    見積書_項目リスト作成画面:exit/メニューに戻る
    見積書_項目リスト作成画面 -[#blue,bold]-> 見積書項目設定画面: 戻る
    見積書_項目リスト作成画面 --> 見積書_項目リストレコード追加画面: [レコードの追加]ボタン押下
    見積書_項目リストレコード追加画面:entry/初期表示
    見積書_項目リストレコード追加画面:exit/リスト作成に戻る
    見積書_項目リストレコード追加画面 --> 見積書_項目リスト作成画面: データ記入\n追加ボタン押下
    見積書_項目リストレコード追加画面 --> 商品詳細表示画面: 商品を選択\n[詳細表示]ボタン押下
    商品詳細表示画面:entry/選択商品の情報取得
    商品詳細表示画面:exit/レコード追加に戻る
    商品詳細表示画面 --> 見積書_項目リストレコード追加画面: OK押下
    見積書_項目リスト作成画面 --> 見積書_項目リストレコード削除画面: [レコード削除]ボタン押下
    見積書_項目リストレコード削除画面:entry/作成済みのレコード番号取得
    見積書_項目リストレコード削除画面:exit/リスト作成に戻る
    見積書_項目リストレコード削除画面 --> 見積書_項目リスト作成画面: レコード選択\n削除押下
}

見積書作成処理系 -[#blue,bold]-> [*]: 作成してメニュー/作成せずにメニュー


@enduml
